const FETCH_DATA  = 'FETCH_DATA';
const ADD_TASK    = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';

const FETCH_DATA_SUCCESS  = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE  = 'FETCH_DATA_FAILURE';
const ADD_TASK_SUCCESS    = 'ADD_TASK_SUCCESS';
const ADD_TASK_FAILURE    = 'ADD_TASK_FAILURE';
const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

const SHOW_DIALOG = 'SHOW_DIALOG';
const HIDE_DIALOG = 'HIDE_DIALOG'

const DATA_ITEM = 'DATA_ITEM'


export {
    FETCH_DATA,
    ADD_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    FETCH_DATA_SUCCESS,
    FETCH_DATA_FAILURE,
    ADD_TASK_SUCCESS,
    ADD_TASK_FAILURE,
    UPDATE_TASK_SUCCESS,
    UPDATE_TASK_FAILURE,
    DELETE_TASK_SUCCESS,
    DELETE_TASK_FAILURE,
    SHOW_DIALOG,
    HIDE_DIALOG,
    DATA_ITEM
}
